[package]
name = "rcwi"
version = "0.1.0"
authors = ["ulf <ulfahammar@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "editor-input",
]

[dependencies]
editor-input = { path = "./editor-input/" }
indicium = "0.3.0"
tui = { version = "0.16.0", features = ["crossterm"] }
crossterm = "0.20"
unicode-width = "0.1"
tokio = { version = "1", features = ["rt"] }
aws-sdk-cloudwatchlogs = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.25-alpha", package = "aws-sdk-cloudwatchlogs" }
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.25-alpha", package = "aws-config" }
flexi_logger = "0.19"
log = "0.4"
time = { version = "0.3", features = ["formatting", "parsing"] }
home = "0.5.3"
arboard = { version = "2", features = ["wayland-data-control"], default-features = false }
